# Generated by Django 4.2.11 on 2024-04-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_id',
            field=models.IntegerField(null=True),
        ),
    ]
