# Generated by Django 4.2.11 on 2024-04-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_jobs_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
