# Generated by Django 4.2.11 on 2024-04-14 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2', '0005_alter_jobs_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brief', models.TextField()),
                ('artical', models.TextField()),
                ('pic', models.ImageField(upload_to='research_pic')),
                ('pdf', models.FileField(upload_to='pdf')),
                ('reshers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
