# Generated by Django 4.2.11 on 2024-04-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_research'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books_un',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=100)),
                ('name_doctor', models.CharField(max_length=100)),
                ('book_pdf', models.FileField(upload_to='book_un')),
            ],
        ),
    ]
