# Generated by Django 4.2.11 on 2024-04-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('instructor', 'instructor'), ('Trainee', 'Trainee')], default='Trainee', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='typee',
            field=models.CharField(choices=[('student', 'student'), ('instructor', 'instructor'), ('Trainee', 'Trainee')], default='student', max_length=30),
        ),
    ]
