# Generated by Django 4.2.11 on 2024-04-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_customuser_role_alter_profile_typee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('instructor', 'instructor'), ('trainee', 'Trainee')], default='trainee', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='typee',
            field=models.CharField(choices=[('student', 'student'), ('instructor', 'instructor'), ('trainee', 'Trainee')], default='student', max_length=30),
        ),
    ]
